apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: clinic-management
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/memory: '1Gi'
        run.googleapis.com/cpu: '1000m'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - name: clinic-management
          image: gcr.io/your-project-id/clinic-management
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: 'crm.settings'
            - name: DEBUG
              value: 'False'
            - name: ALLOWED_HOSTS
              value: '*'
            - name: SECRET_KEY
              value: 'your-secret-key-here'
            - name: DATABASE_URL
              value: 'your-database-url-here'
          # Add more environment variables as needed
          # - name: GOOGLE_CLOUD_PROJECT
          #   value: "your-project-id"
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /admin/login/
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /admin/login/
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
