# Generated by Django 5.2.1 on 2025-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patient_bp_patient_height_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
