# Generated by Django 5.2.1 on 2025-05-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_medicationentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='BP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
