# Generated by Django 5.2.1 on 2025-05-25 14:44

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_patient_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='custom_id',
            field=models.CharField(default=home.models.generate_custom_id, editable=False, max_length=50, unique=True),
        ),
    ]
