# Generated by Django 5.2.1 on 2025-05-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_patient_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BP',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
