# Generated by Django 5.2.1 on 2025-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_patient_bp'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_unit',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='years', max_length=10),
        ),
    ]
