# Generated by Django 5.2.1 on 2025-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_patient_age_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_unit',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default='N/A', max_length=25),
        ),
    ]
