# Generated by Django 5.1.5 on 2025-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_patient_age_unit_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('chief_complaints', 'Chief Complaints'), ('investigation', 'Investigation'), ('examination_findings', 'Examination Findings'), ('diagnosis', 'Diagnosis'), ('treatment_plan', 'Treatment Plan'), ('advice', 'Advice'), ('medication', 'Medication')], max_length=50)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
